language: perl
os:
  - linux
#  - osx    #doesn’t install the correct perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
#  - "5.8"
#  - "5.6"
#before_install:
#    - "sudo apt-get install pkg-config"
#    - "sudo apt-get install apt-file unbound libunbound-dev"
#    - "apt-file update"
#    - "apt-file show libunbound-dev"
# Travis CI’s libunbound-dev package lacks a .pc file,
# so let’s install from source instead.
before_install:
    - "wget https://nlnetlabs.nl/downloads/unbound/unbound-latest.tar.gz -O /tmp/unbound.tar.gz"
    - "tar -xvzf /tmp/unbound.tar.gz"
    - "pushd /tmp && ./configure && make && sudo make install && popd"
install:
    - cpanm --verbose --installdeps --notest .
matrix:
  include:
    - os: osx
      perl: system
      addons:
        homebrew:
          packages:
            - unbound
      before_install:
        - "curl -L http://cpanmin.us | perl - --self-upgrade"
        - export PATH=$PATH:$HOME/perl5/bin
        - "cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)"
