name: BSDs

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
    PERL_USE_UNSAFE_INC: 0
    AUTHOR_TESTING: 0
    AUTOMATED_TESTING: 1
    RELEASE_TESTING: 0
    PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

jobs:
  test:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '12.2'
            pkginstall: pkg install -y unbound perl5
          - name: freebsd
            version: '13.0'
            pkginstall: pkg install -y unbound perl5
          - name: openbsd
            version: '6.9'
            pkginstall: pkg_add libunbound pkg-config
#          - name: netbsd
#            version: '9.2'
#            pkginstall: pkg_add libunbound

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Test on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.3.1
        env:
          GITHUB_SERVER_URL: $GITHUB_SERVER_URL
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        with:
          environment_variables: GITHUB_SERVER_URL GITHUB_REPOSITORY
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo ${{ matrix.os.pkginstall }}
            curl -L https://cpanmin.us | sudo perl - --notest --installdeps --with-configure --with-develop .
            perl Makefile.PL
            make
            prove -wlvmb t
